name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published
jobs:
  tests:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        plugin-manager:
          - fisher
          - oh-my-fish
          - plug.fish
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install fish shell
        uses: fish-actions/install-fish@v1.1.0
      - if: matrix.plugin-manager != 'oh-my-fish' && github.event_name == 'pull_request'
        name: Install plugin using <username>/<repo> name and action from pull-request
        uses: ./.
        with:
          plugin-manager: ${{ matrix.plugin-manager }}
          plugins: marcransome/pond
      - if: matrix.plugin-manager != 'oh-my-fish' && github.event_name != 'pull_request'
        name: Install plugin using <username>/<repo> name and action from main branch
        uses: fish-shop/install-plugin@main
        with:
          plugin-manager: ${{ matrix.plugin-manager }}
          plugins: marcransome/pond
      - if: matrix.plugin-manager == 'oh-my-fish' && github.event_name == 'pull_request'
        name: Install plugin using URL and action from pull-request
        uses: ./.
        with:
          plugin-manager: ${{ matrix.plugin-manager }}
          plugins: https://github.com/marcransome/pond
      - if: matrix.plugin-manager == 'oh-my-fish' && github.event_name != 'pull_request'
        name: Install plugin using URL and action from main branch
        uses: fish-shop/install-plugin@main
        with:
          plugin-manager: ${{ matrix.plugin-manager }}
          plugins: https://github.com/marcransome/pond
      - name: Check plugin installed
        run: type -q pond
        shell: fish {0}
